services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: voca
      POSTGRES_USER: voca
      POSTGRES_PASSWORD: voca
    ports:
      - "5432:5432"
