server:
  port: 8080

spring:
  application:
    name: voca-note

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:vocab}
    username: ${POSTGRES_USER:vocab}
    password: ${POSTGRES_PASSWORD:vocab}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: INFO


app:
  external:
    datamuse:
      base-url: https://api.datamuse.com
    dictionary:
      base-url: https://api.dictionaryapi.dev
    deepl:
      base-url: ${DEEPL_BASE_URL:https://api-free.deepl.com}
      auth-key: ${DEEPL_AUTH_KEY:19A7C3VBlYQni1JSm}
      timeout: 3s
      target-lang: KO
